name: test
# This action should only be called on a pull request against the master branch (allows WIP pushes without triggering CI)
on:
  push:
    branches: ci
  
jobs:
  test-cert-manager:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev      
    - name: switch to CI branch
      run: |
        git fetch origin ci:ci
        git reset --hard ci    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3       
      with:
        base: dev
        labels: automerge 
        branch: ci-promotion-to-dev
