name: test
# This action should only be called on a pull request against the master branch (allows WIP pushes without triggering CI)
on:
  push:
    branches: ci
  
jobs:
  test-cert-manager:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3       
      with:
        branch: dev
        labels: automerge 